Added new case to the iterative write tutorial
NeurodataWithoutBorders/pynwb pull request #1029
Opened 2019-07-30 19:26 UTC by oruebel

## Motivation

Add stale changes from #515 to iterative write tutorial. 

## How to test the behavior?
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```

## Checklist

- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [ ] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [ ] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

2019-07-30 19:56 UTC, oruebel commented
This is waiting for fixes in https://github.com/hdmf-dev/hdmf/pull/121 to be merged for the tests to pass

2019-08-21 07:09 UTC, oruebel commented
@rly @ajtritt I believe this PR was only waiting for a release of HDMF to fix tests. Since the tests are passing now, I believe this PR should be good to go.

2019-08-21 14:17 UTC, ajtritt requested changes

2019-08-21 14:17 UTC, ajtritt commented on docs/gallery/general/iterative_write.py
> +# This approach is useful when we need to optimize the write but it may also exposes I/O backend-specifics
I think this is a typo or a poorly worded sentence.

2019-09-28 00:50 UTC, rly approved these changes

2019-09-28 00:51 UTC, ajtritt approved these changes

2019-10-02 22:46 UTC, merged