adds save "methods" w/ to_X syntax #117
NeurodataWithoutBorders/pynwb pull request #121
Opened 2017-09-21 20:19 UTC by neuromusic

no unit tests or documentation, but I manually tested that the implementation works in 2.7 & 3.6

this makes the assumption that new backends will conform to the module structure of the HDF5IO backend. specifically: a module with a single class

this specifically addresses @ajtritt's concern in #117 that "For every backend, we have to edit NWBFile to add some new to_<backend> method to it."

2017-09-21 20:23 UTC, neuromusic commented
example use:

``` Python
from datetime import datetime
from pynwb import NWBFile

nwb = NWBFile('the PyNWB tutorial', 'my first synthetic recording', 'EXAMPLE_ID', datetime.now(),
            experimenter='Dr. Bilbo Baggins',
            lab='Bag End Labatory',
            institution='University of Middle Earth at the Shire',
            experiment_description='I went on an adventure with thirteen dwarves to reclaim vast treasures.',
            session_id='LONELYMTN')

nwb.to_hdf5('example.nwb')
```

2017-11-07 19:52 UTC, jcfr requested changes
Please, rebase and squash the commit together. 

I also suggest you install and run `flake8` locally to fix the style.

```
$ pip install flake8
$ flake8
```

2017-11-07 20:47 UTC, neuromusic commented
thanks @jcfr but I don't think @ajtritt wants this PR merged in (see the convo in #117)

2017-11-07 21:10 UTC, oruebel commented
Yes, I believe this pull request is superseded by #171

2017-11-07 21:12 UTC, neuromusic commented
to be clear, #171 does not address #117 

perhaps this should stay open until #117 is resolved?

2017-11-08 15:21 UTC, jcfr commented
Commit have been squashed, style fixed and topic updated.

2017-11-08 15:21 UTC, jcfr commented on src/pynwb/file.py
> +            if ismodule(obj) & hasattr(obj, '__path__'):
`&` -> `and`

2017-11-08 15:23 UTC, jcfr commented on src/pynwb/file.py
> +            if ismodule(obj) & hasattr(obj, '__path__'):
Could you add a `is_backend` function ? This seems to be a fragile way of checking if an object is  a backend

2017-11-08 15:24 UTC, jcfr commented on src/pynwb/file.py
> +                        if issubclass(obj2, FORMIO):
Adding a `is_backend_io` function may be relevant too.

Also since there is a test on subclass, not sure why catching `TypeError` is needed

2017-11-08 15:27 UTC, jcfr requested changes
Improve robustness and adding tests would be ideal

2018-04-10 16:42 UTC, closed without merging