add dummy data for ecephys
NeurodataWithoutBorders/pynwb pull request #1454
Opened 2022-04-15 17:54 UTC by bendichter

## Motivation

fix #1452 

I tried fixtures first but it was very difficult to get them to play nice with unitTests.

2022-04-19 13:04 UTC, bendichter commented
I'm happy with the flexibility of this approach. I think this could help minimize a l of testing code across several repos, including PyNWB, NWB Widgets, and NWB Inspector.

Questions:
* How do people feel about this naming convention?
* Should we try to automate creation from docval?

2022-08-24 19:02 UTC, bendichter commented on tests/unit/test_misc.py
> +    def mock_electrode_table(self):
```suggestion
    def make_electrode_table(self):
```

2022-08-24 19:03 UTC, bendichter commented on tests/unit/test_misc.py
> +        self.mock_electrode_table(self)
```suggestion
        self.make_electrode_table(self)
```

2022-08-31 02:05 UTC, bendichter commented
@rly and @oruebel this is ready for review

2022-08-31 15:17 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +    return table
```suggestion
def mock_ElectrodeTable(n_rows=5, group=None):
    table = ElectrodeTable()
    for i in range(n_rows):
        table.add_row(
            location="CA1",
            group=group if group is not None else mock_ElectrodeGroup(),
            group_name=group.name,
        )
    return table
```

2022-08-31 15:27 UTC, oruebel requested changes
Several of the mock classes use mutable default arguments (e.g., numpy arrays). To avoid possible "gotchas" and unexpected behavior it would be useful to replace those with ``None`` and set the default value inside the function.

2022-08-31 15:28 UTC, oruebel commented on src/pynwb/testing/mock/base.py
> +    data=np.array([1, 2, 3, 4]),
```suggestion
    data=None,
```

2022-08-31 15:28 UTC, oruebel commented on src/pynwb/testing/mock/base.py
> +        data=data,
```suggestion
        data=data if data is not None else np.array([1, 2, 3, 4]),
```

2022-08-31 15:29 UTC, oruebel commented on src/pynwb/testing/mock/behavior.py
> +    data=np.array([1, 2, 3, 4]),
```suggestion
    data=None,
```

2022-08-31 15:29 UTC, oruebel commented on src/pynwb/testing/mock/behavior.py
> +        data=data,
```suggestion
        data=data if data is not None else np.array([1, 2, 3, 4]),
```

2022-08-31 15:30 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +    data=np.ones((10, 5)),
```suggestion
    data=None,
```

2022-08-31 15:30 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +        data=data,
```suggestion
        data=data if data is not None else np.ones((10, 5)),
```

2022-08-31 15:30 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +    data=np.ones((10, 5)),
```suggestion
    data=None,
```

2022-08-31 15:31 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +        data=data,
```suggestion
        data=data if data is not None else np.ones((10, 5)),
```

2022-08-31 15:31 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +    timestamps=np.arange(10).astype(float),
```suggestion
    timestamps=None,
```

2022-08-31 15:31 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +        timestamps=timestamps,
```suggestion
        timestamps=timestamps if timestamps is not None else np.arange(10).astype(float),
```

2022-08-31 15:32 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +    electrodes=mock_electrodes(),
```suggestion
    electrodes=None,
```

2022-08-31 15:32 UTC, oruebel commented on src/pynwb/testing/mock/ecephys.py
> +        electrodes=electrodes,
```suggestion
        electrodes=electrodes if electrodes is not None else mock_electrodes(),
```

2022-08-31 15:33 UTC, oruebel commented on src/pynwb/testing/mock/ogen.py
> +    data=np.array([1, 2, 3, 4]),
```suggestion
    data=None,
```

2022-08-31 15:33 UTC, oruebel commented on src/pynwb/testing/mock/ogen.py
> +        data=data,
```suggestion
        data=data if data is not None else np.array([1, 2, 3, 4]),
```

2022-08-31 15:34 UTC, oruebel commented on src/pynwb/testing/mock/ophys.py
> +    name=name_generator("TwoPhotonSeries"),
```suggestion
    name=None,
```

2022-08-31 15:34 UTC, oruebel commented on src/pynwb/testing/mock/ophys.py
> +        name=name,
```suggestion
        name=name if name is not None else name_generator("TwoPhotonSeries"),
```

2022-08-31 15:34 UTC, oruebel commented on src/pynwb/testing/mock/ophys.py
> +    name=name_generator("PlaneSegmentation"),
```suggestion
    name=None,
```

2022-08-31 15:35 UTC, oruebel commented on src/pynwb/testing/mock/ophys.py
> +        name=name,
```suggestion
        name=name if name is not None else name_generator("PlaneSegmentation"),
```

2022-08-31 15:35 UTC, oruebel commented on src/pynwb/testing/mock/ophys.py
> +    data=np.ones((30, 5)),
```suggestion
    name=None,
    data=None,
```

2022-08-31 15:36 UTC, oruebel commented on src/pynwb/testing/mock/ophys.py
> +        data=data,
```suggestion
        name=name if name is not None else name_generator("RoiResponseSeries"),
        data=data if data is not None else np.ones((30, 5)),
```

2022-08-31 15:36 UTC, oruebel commented on src/pynwb/testing/mock/ophys.py
> +def mock_DfOverF(roi_response_series=None, name=name_generator("DfOverF")):
```suggestion
def mock_DfOverF(roi_response_series=None, name=None):
```

2022-08-31 15:36 UTC, oruebel commented on src/pynwb/testing/mock/ophys.py
> +        name=name,
```suggestion
        name=name if name is not None else name_generator("DfOverF"),
```

2022-08-31 15:38 UTC, bendichter commented on src/pynwb/testing/mock/ophys.py
> +        name=name,
```suggestion
def mock_Fluorescence(roi_response_series=None, name=None):
    return Fluorescence(
        roi_response_series=roi_response_series or [mock_RoiResponseSeries()],
        name=name if name is not None else name_generator("Fluorescence"),
```

2022-08-31 15:52 UTC, oruebel requested changes
@bendichter could you add a docstring at least at the top of each module (py-file) to describe what the module contains and how to use it. It would be nice to also have docstrings for each of the functions, but I think in this particular case that is less critical as the functions are more-or-less self-describing once you know what the purpose of a ``mock_X`` function is.

Otherwise this looks good to me. Thanks for putting this together.

2022-09-16 02:14 UTC, bendichter commented on src/pynwb/testing/mock/__init__.py
> +This module provides mock instance of common neurodata types which can be used to write
```suggestion
The mock module provides mock instances of common neurodata types which can be used to write
```

2022-09-16 03:01 UTC, oruebel requested changes
Can you please update the Changelog. Otherwise this looks good to me.

2022-09-16 04:35 UTC, oruebel approved these changes

2022-09-16 04:36 UTC, merged