Add issue and pull request templates
NeurodataWithoutBorders/pynwb pull request #177
Opened 2017-11-01 16:42 UTC by dorukozturk

As an example I am following the PR template:

## Motivation

This change was added to formalize and unify the Pull Request and Issue creation process for the contributors. 

## How to test the behavior?

This feature can be tested once this PR is merged on "dev" branch. A simple test can be creating a new issue to see whether the template is recommended or not. 

## Checklist

- [x] Have you checked our Contributing document?
- [x] Have you checked to ensure there aren't other open Pull Request for the same change?
- [x] Does your submission pass all tests?
- [x] Have you added an explanation of what your changes are?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you address the corresponding issue in your Pull Request?

2017-11-01 17:04 UTC, dorukozturk commented
@ajtritt and @oruebel Do the templates look good to you? I can add or remove items based on your comments.

2017-11-01 17:15 UTC, oruebel reviewed
For the feature request, rather than asking for the wanted feature and implementation details, I would lead of with:

* **What problem/use-case are you trying to solve**. Describing the use case is often more important than proposing a specific solution. By describing the use case and problem you are trying to solve gives the development team and ultimately the NWB:N community a better understanding for the reasons of changes and enables other to suggest solutions.
* Instead of wanted feature, I would then change it to **Suggested Feature**

2017-11-01 17:20 UTC, oruebel commented
BTW, you may also want to have a look at https://github.com/NeurodataWithoutBorders/pynwb/pull/172 to make sure we are consistent in the template and contributing guidelines.  Just let me know in case we need to updated the contributing guidelines.

2017-11-01 17:28 UTC, dorukozturk commented
@oruebel I think matching with the Contribution document makes a lot of sense. I will follow your contribution format.

2017-11-01 17:30 UTC, oruebel commented
@dorukozturk if there are things that you think needs to be changed in the contributing guidelines that's fine too. Any suggestions are welcome.

2017-11-01 17:46 UTC, jcfr commented
May be worth referencing http://sscce.org/

2017-11-01 18:07 UTC, ajtritt commented
I agree with @oruebel about describing the problem and use-case in the issue template. 

Can we add a section to the PR template that asks for a brief description of what has been changed. It could also just be added to the Motivation section. When reviewing a PR, it's nice to have a high-level overview of what's been changed.

2017-11-01 18:14 UTC, mgrauer requested changes

2017-11-01 18:14 UTC, mgrauer commented on .github/PULL_REQUEST_TEMPLATE.md
> +Show here how to reproduce the new behavior(can be a bug fix or a new feature)
should be `behavior (`, i.e., add a space

2017-11-01 18:14 UTC, mgrauer commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Have you checked to ensure there aren't other open Pull Request for the same change?
Requests

2017-11-01 18:14 UTC, mgrauer commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Have you address the corresponding issue in your Pull Request?
addressed

2017-11-07 13:19 UTC, dorukozturk commented
@oruebel Does this look good now?

2017-11-08 14:29 UTC, jcfr commented on docs/ISSUE_TEMPLATE.md
> +- **Operating System:** Windows, Mac or Linux
macOS

2017-11-08 14:30 UTC, jcfr commented on docs/ISSUE_TEMPLATE.md
> +Describe the feature needed briefly as well as the reasoning behind it.
Briefly describe the needed feature as well as the reasoning behind it

2017-11-08 14:31 UTC, jcfr commented on docs/ISSUE_TEMPLATE.md
> +- [ ] Have you ensured the feature or change was not already reported?
```
[reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/)
```

2017-11-08 14:32 UTC, jcfr commented on docs/ISSUE_TEMPLATE.md
> +- [ ] Have you selected the correct label for your issue?
I don't think external contributor can select label

2017-11-08 14:37 UTC, jcfr commented on docs/ISSUE_TEMPLATE.md
> +- [ ] Have you followed [pep8](https://www.python.org/dev/peps/pep-0008/) ?
```
- [ ] Is your contribution compliant with out coding style ? This can be checked running `flake8` from the source directory.
```

2017-11-08 14:38 UTC, jcfr commented on docs/PULL_REQUEST_TEMPLATE.md
> +- [ ] Have you checked our Contributing document?
- [ ] Have you checked our Contributing document? See link above.

2017-11-08 14:39 UTC, jcfr commented on docs/ISSUE_TEMPLATE.md
> +- [ ] Have you followed [pep8](https://www.python.org/dev/peps/pep-0008/) ?
Look like this should be added only to the PR template.

2017-11-08 14:40 UTC, jcfr commented on docs/PULL_REQUEST_TEMPLATE.md
> +- [ ] Have you checked to ensure that there aren't other open Pull Requests for the same change?
Add link to PRs

2017-11-08 14:40 UTC, jcfr commented on docs/PULL_REQUEST_TEMPLATE.md
> +- [ ] Have you ensured that the code follows the standard coding style?
See above.

2017-11-08 14:41 UTC, jcfr commented on docs/PULL_REQUEST_TEMPLATE.md
> +- [ ] Have you included the relevant issue number?
```
- [ ] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?
```

2017-11-08 14:42 UTC, jcfr requested changes
Few nitpick and this should be good to go

2017-11-08 15:05 UTC, mgrauer commented
This is probably minor, but since external contributors can't apply labels, do we want them to suggest labels in text to make it easier on maintainers, or would this be low yield?

2017-11-08 15:05 UTC, dorukozturk commented
@jcfr I think this is ready

2017-11-08 15:33 UTC, merged