[WIP] adds reference_images kwarg as attribute for ROI. fixes #307
NeurodataWithoutBorders/pynwb pull request #308
Opened 2017-12-20 19:00 UTC by neuromusic

## Motivation

fixes #307 

## How to test the behavior?
```
import numpy as np

NA = 'THIS REQUIRED ATTRIBUTE INTENTIONALLY LEFT BLANK.'

from pynwb import image, ophys
max_proj = image.ImageSeries(
    name = 'Maximum Projection Image',
    source = NA,
    data = np.random.rand(10,10),
    unit = NA,
    format = 'raw',
    timestamps = [0.0], 
)

roi = ophys.ROI(
    name = NA,
    source = NA,
    roi_description = NA,
    pix_mask = [],
    pix_mask_weight = [],
    img_mask = np.random.rand(10,10),
    reference_images = max_proj, 
)

print roi.reference_images
```

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [ ] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

2017-12-20 19:03 UTC, neuromusic commented
This seems to fix the problem, but I could use some guidance writing the appropriate tests for this issue.

2017-12-20 19:44 UTC, ajtritt submitted a review, later dismissed
This looks great! Exactly how it should be done... nice work

2017-12-20 19:45 UTC, neuromusic commented
thanks @ajtritt.

it looks like there's no unit test coverage for ROI at all. I'll get that added in then this should be ready to go.

2017-12-20 19:49 UTC, ajtritt commented
@neuromusic check out pynwb/tests/unit/pynwb_tests/test_ophys.py, if you haven't found it yet. This would be appropriate place for the unit test(s) for ROI

2017-12-20 21:47 UTC, neuromusic commented
ready for review & merge

2017-12-21 22:50 UTC, neuromusic commented
so this PR works for creating the object, but something is going wrong on write.

the following example fails on read:

``` Python
Jupyter Notebook
ROI_error
Last Checkpoint: Yesterday at 10:11 AM
(unsaved changes)
ophys_nwb
Logout
ophys_nwb Kernel readyTrusted
File
Edit
View
Insert
Cell
Kernel
Widgets
Help
Run
In [*]:

import numpy as np
​
NA = 'THIS REQUIRED ATTRIBUTE INTENTIONALLY LEFT BLANK.'
​
from pynwb import image, ophys
max_proj = image.ImageSeries(
    name = 'Maximum Projection Image',
    source = NA,
    data = np.random.rand(10,10),
    unit = NA,
    format = 'raw',
    timestamps = [0.0], # <- This is required, so let's make it at the beginning of the experiment
)
​
roi = ophys.ROI(
    name = NA,
    source = NA,
    roi_description = NA,
    pix_mask = [],
    pix_mask_weight = [],
    img_mask = np.random.rand(10,10),
    reference_images = max_proj, # <- Ugh, I need to define reference image(s) just to define an ROI?
)
​
print roi.reference_images
​
import datetime as dt
from pynwb import NWBFile
nwb = NWBFile(
    source = NA,
    session_description = NA,
    identifier = NA,
    session_start_time = dt.datetime.now(),
)
​
ophys_module = nwb.create_processing_module(
    name="ophys",
    description=NA,
    source=NA,
)
ophys_module.add_container(roi)
​
from pynwb import NWBHDF5IO as HDF5IO
fname = 'roi_test.nwb'
io = HDF5IO(fname,mode='w')
io.write(nwb)
io.close()
​
reader = HDF5IO(fname,mode='r')
nwb_out = reader.read()
reader.close()
```

here's the error I get on `reader.read()`

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-14a3a14a91c4> in <module>()
     48 
     49 reader = HDF5IO(fname,mode='r')
---> 50 nwb_out = reader.read()
     51 reader.close()

/local1/Code/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    304                     msg = ', '.join(parse_err)
    305                     raise_from(TypeError(msg), None)
--> 306                 return func(self, **parsed['args'])
    307         else:
    308             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/form/backends/io.pyc in read(self, **kwargs)
     30     def read(self, **kwargs):
     31         f_builder = self.read_builder()
---> 32         container = self.__manager.construct(f_builder)
     33         return container
     34 

/local1/Code/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    304                     msg = ', '.join(parse_err)
    305                     raise_from(TypeError(msg), None)
--> 306                 return func(self, **parsed['args'])
    307         else:
    308             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in construct(self, **kwargs)
     66         result = self.__containers.get(builder_id)
     67         if result is None:
---> 68             result = self.__type_map.construct(builder, self)
     69             self.prebuilt(result, builder)
     70         return result

/local1/Code/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    304                     msg = ', '.join(parse_err)
    305                     raise_from(TypeError(msg), None)
--> 306                 return func(self, **parsed['args'])
    307         else:
    308             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in construct(self, **kwargs)
   1012                              % str(container.__class__.__name__))  # noqa: F821
   1013         else:
-> 1014             return attr_map.construct(builder, build_manager)
   1015 
   1016     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

/local1/Code/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    304                     msg = ', '.join(parse_err)
    305                     raise_from(TypeError(msg), None)
--> 306                 return func(self, **parsed['args'])
    307         else:
    308             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in construct(self, **kwargs)
    615         cls = manager.get_cls(builder)
    616         # gather all subspecs
--> 617         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    618         # get the constructor argument each specification corresponds to
    619         const_args = dict()

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in __get_subspec_values(self, builder, spec, manager)
    601                             ret[subspec] = val
    602                     else:
--> 603                         result = self.__get_subspec_values(sub_builder, subspec, manager)
    604                         ret.update(result)
    605         else:

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in __get_subspec_values(self, builder, spec, manager)
    592                     if self.__data_type_key in sub_builder.attributes or \
    593                        not (subspec.data_type_inc is None and subspec.data_type_def is None):
--> 594                         val = manager.construct(sub_builder)
    595                         if subspec.is_many():
    596                             if subspec in ret:

/local1/Code/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    304                     msg = ', '.join(parse_err)
    305                     raise_from(TypeError(msg), None)
--> 306                 return func(self, **parsed['args'])
    307         else:
    308             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in construct(self, **kwargs)
     66         result = self.__containers.get(builder_id)
     67         if result is None:
---> 68             result = self.__type_map.construct(builder, self)
     69             self.prebuilt(result, builder)
     70         return result

/local1/Code/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    304                     msg = ', '.join(parse_err)
    305                     raise_from(TypeError(msg), None)
--> 306                 return func(self, **parsed['args'])
    307         else:
    308             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in construct(self, **kwargs)
   1012                              % str(container.__class__.__name__))  # noqa: F821
   1013         else:
-> 1014             return attr_map.construct(builder, build_manager)
   1015 
   1016     @docval({"name": "container", "type": Container, "doc": "the container to convert to a Builder"},

/local1/Code/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    304                     msg = ', '.join(parse_err)
    305                     raise_from(TypeError(msg), None)
--> 306                 return func(self, **parsed['args'])
    307         else:
    308             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in construct(self, **kwargs)
    615         cls = manager.get_cls(builder)
    616         # gather all subspecs
--> 617         subspecs = self.__get_subspec_values(builder, self.spec, manager)
    618         # get the constructor argument each specification corresponds to
    619         const_args = dict()

/local1/Code/pynwb/src/pynwb/form/build/map.pyc in __get_subspec_values(self, builder, spec, manager)
    592                     if self.__data_type_key in sub_builder.attributes or \
    593                        not (subspec.data_type_inc is None and subspec.data_type_def is None):
--> 594                         val = manager.construct(sub_builder)
    595                         if subspec.is_many():
    596                             if subspec in ret:

/local1/Code/pynwb/src/pynwb/form/utils.pyc in func_call(*args, **kwargs)
    304                     msg = ', '.join(parse_err)
    305                     raise_from(TypeError(msg), None)
--> 306     [...]

2018-01-15 20:27 UTC, neuromusic commented
OK @ajtritt since chatting with you about this more last week:

This PR fixes the specific issue noted in #307: accessing the attribute after the ROI is created. I'm going to open up a new issue for the "Could not construct ROI object" error, as that seems to be out-of-scope for my knowledge and this PR.

If that sounds good, this is ready to approve and merge.

2018-01-16 17:52 UTC, ajtritt requested changes
Just remove `reference_images` from ROI constructor

2018-01-16 17:57 UTC, ajtritt commented
I just realized that `reference_images` isn't a field under [ROI in the spec](http://nwb-schema.readthedocs.io/en/latest/format.html#groups-planesegmentation-roi). 

I'm not sure how this found it's way in there, but this should only be required by the [PlaneSegmentation constructor](http://pynwb.readthedocs.io/en/latest/pynwb.ophys.html#pynwb.ophys.PlaneSegmentation).

I suspect that this may be the cause of #326

2018-01-16 19:55 UTC, neuromusic commented
So the problem is that the docval on the ROI class has `reference_images`.

FML

I'll update this PR.

2018-01-17 00:17 UTC, neuromusic commented
ok @ajtritt this should be ready to merge

2018-01-17 00:21 UTC, ajtritt approved these changes

2018-01-17 00:21 UTC, merged