Enhance icephys domain specific example
NeurodataWithoutBorders/pynwb pull request #432
Opened 2018-04-05 19:56 UTC by t-b

## Motivation

The example was missing a few things.

## How to test the behavior?
```
python icephys.py
```
and then look at the HDF5 file.

2018-04-05 19:56 UTC, pep8speaks commented
Hello @t-b! Thanks for updating the PR.



Cheers ! There are no PEP8 issues in this Pull Request. :beers: 

##### Comment last updated on April 13, 2018 at 20:05 Hours UTC

2018-04-10 16:47 UTC, ajtritt requested changes
Fix PEP8 issue

2018-04-10 16:47 UTC, ajtritt commented on docs/gallery/domain/icephys.py
> +    unit='A', conversion=1e-12, resolution=np.nan, starting_time=123.6, rate=20e3,
Indent these lines to satisfy PEP8, and this should be good to go.

2018-04-13 20:06 UTC, t-b commented on docs/gallery/domain/icephys.py
> +    unit='A', conversion=1e-12, resolution=np.nan, starting_time=123.6, rate=20e3,
@ajtritt Done.

2018-04-13 20:39 UTC, merged