Unitwise metrics
NeurodataWithoutBorders/pynwb pull request #435
Opened 2018-04-05 23:54 UTC by NileGraddis

Resolves #427 

Adds a generic class for unit-wise metrics (such as the mean firing rate of a sorted ephys unit) and a specialization for peak_over_rms (the existing version of a unit metric). Adds a Multicontainer Interface for storing these metrics, which also stores a link to a unittimes group. Adds unit and integration tests for theses features

2018-04-05 23:54 UTC, pep8speaks commented
Hello @NileGraddis! Thanks for submitting the PR.

 - In the file [`src/pynwb/misc.py`](https://github.com/NeurodataWithoutBorders/pynwb/blob/63e214399ae96125227d1408d69f57b18af9a01d/src/pynwb/misc.py), following are the PEP8 issues :

> [Line 154:88](https://github.com/NeurodataWithoutBorders/pynwb/blob/63e214399ae96125227d1408d69f57b18af9a01d/src/pynwb/misc.py#L154): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ':'
> [Line 156:73](https://github.com/NeurodataWithoutBorders/pynwb/blob/63e214399ae96125227d1408d69f57b18af9a01d/src/pynwb/misc.py#L156): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ':'
> [Line 204:9](https://github.com/NeurodataWithoutBorders/pynwb/blob/63e214399ae96125227d1408d69f57b18af9a01d/src/pynwb/misc.py#L204): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 256:9](https://github.com/NeurodataWithoutBorders/pynwb/blob/63e214399ae96125227d1408d69f57b18af9a01d/src/pynwb/misc.py#L256): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 272:9](https://github.com/NeurodataWithoutBorders/pynwb/blob/63e214399ae96125227d1408d69f57b18af9a01d/src/pynwb/misc.py#L272): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line
> [Line 302:9](https://github.com/NeurodataWithoutBorders/pynwb/blob/63e214399ae96125227d1408d69f57b18af9a01d/src/pynwb/misc.py#L302): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line

2018-04-13 22:29 UTC, ajtritt requested changes

2018-04-13 22:29 UTC, ajtritt commented on src/pynwb/data/nwb.misc.yaml
> +- neurodata_type_def: UnitMetric
Can we add a required description field here? If we allow for arbitrary metrics, we should also require that users provide a description of the metric they are storing.

2018-04-13 22:43 UTC, tjd2002 commented
Per discussion with @NileGraddis it seems like a good idea to expand this PR ago also include the proposed Unit class discussed at #431 . While this class would stand alone it seems preferable to refactor all the Unit-wise stuff together.

2018-04-13 22:46 UTC, tjd2002 commented on src/pynwb/data/nwb.misc.yaml
> +- neurodata_type_def: UnitMetric
Agreed

2018-09-12 21:27 UTC, bendichter commented
@ajtritt can we close this?

2018-09-25 23:38 UTC, closed without merging