names cannot include '/'
NeurodataWithoutBorders/pynwb pull request #478
Opened 2018-04-21 19:10 UTC by bendichter

The '/' character causes a problem for names of datasets because h5py interprets and creates subgroups, which is not the desired behavior.

Add ValueError in constructor for all data objects if '/' is present
Add test that '/' raises error

## Motivation

fix #129 

## How to test the behavior?
```python
from pynwb import NWBContainer
NWBContainer('a', 'b/c')
```
should raise: `ValueError: name 'b/c' cannot contain '/'`

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

2018-04-23 17:33 UTC, ajtritt approved these changes

2018-04-24 15:08 UTC, neuromusic commented
💯

2018-04-24 18:11 UTC, ajtritt requested changes
This should now go in Container, in src/pynwb/form/container.py

2018-04-24 19:54 UTC, ajtritt commented
addressed in #482

2018-04-24 19:54 UTC, closed without merging