Extensions examples
NeurodataWithoutBorders/pynwb pull request #487
Opened 2018-04-25 20:33 UTC by bendichter

add cortical surface example to Extensions tutorial

2018-04-25 20:33 UTC, pep8speaks commented
Hello @bendichter! Thanks for submitting the PR.

 - In the file [`docs/gallery/general/extensions.py`](https://github.com/NeurodataWithoutBorders/pynwb/blob/8238f9674e1e7f8ea0f5c89f0aa2f0376b85967d/docs/gallery/general/extensions.py), following are the PEP8 issues :

> [Line 158:8](https://github.com/NeurodataWithoutBorders/pynwb/blob/8238f9674e1e7f8ea0f5c89f0aa2f0376b85967d/docs/gallery/general/extensions.py#L158): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent

2018-04-26 20:00 UTC, nicain requested changes

2018-04-26 20:00 UTC, nicain commented on docs/gallery/general/extensions.py
> +# Here we show how to create extensions by example by creating a data class for a
typo: "by example by"

2018-04-26 20:00 UTC, nicain commented on docs/gallery/general/extensions.py
> +# we need to know where each electrode is with respect to the gyri and sucli.
change "we need" to "because we need"?

2018-04-26 20:00 UTC, nicain commented on docs/gallery/general/extensions.py
> +# points defines a triangular face, and the mesh is comprised of a collection of triangular faces.
Reminds me of this: http://paulbourke.net/dataformats/ply/

2018-04-26 20:00 UTC, nicain commented on docs/gallery/general/extensions.py
> +# which is the lowest type you are likely to use as a base. The name of the
"lowest"; what does this mean?  Least complicated?

2018-04-26 20:00 UTC, nicain commented on docs/gallery/general/extensions.py
> +# Now we set up the builder and add this object
add a "#######" above if you want sphinx-gallery to separate, as opposed to inline code comment

2018-04-26 20:00 UTC, nicain commented on docs/gallery/general/extensions.py
> +#
Not sure how this will typeset; maybe use the prototype tool, just to make sure it looks how you want

2019-07-30 19:34 UTC, oruebel commented
@bendichter  What is the status of this PR. Looks like there are a few simple typos but otherwise good to go.

2019-08-09 01:49 UTC, bendichter commented on docs/gallery/general/extensions.py
> +# Here we show how to create extensions by example by creating a data class for a
```suggestion
# Here we show how to create extensions by creating a data class for a
```

2019-08-09 14:31 UTC, bendichter commented
closed in favor of #1040

2019-08-09 14:31 UTC, closed without merging