[WIP] add Image type and subtypes GrayScaleImage, RGBImage, RGBAImage
NeurodataWithoutBorders/pynwb pull request #693
Opened 2018-10-30 17:46 UTC by bendichter

* add Image to core.base
* add GrayscaleImage, RGBImage, and RGBAImage to core.image
* add pynwb support for Image, Images, GrayscaleImage, RGBImage, and RGBAImage

TODO: add tests

## Motivation

fix https://github.com/NeurodataWithoutBorders/nwb-schema/issues/143, fix https://github.com/NeurodataWithoutBorders/nwb-schema/issues/129

## Checklist

- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [x] Have you ensured the PR description clearly describes problem and the solution?
- [x] Is your contribution compliant with our coding style ? This can be checked running `flake8` from the source directory.
- [x] Have you checked to ensure that there aren't other open [Pull Requests](https://github.com/NeurodataWithoutBorders/pynwb/pulls) for the same change?
- [x] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number ?

2018-10-30 18:25 UTC, oruebel submitted a review, later dismissed

2018-10-30 18:25 UTC, oruebel commented on src/pynwb/image.py
> +        self.description = description
You could just pass resolution, data, description to the  super(Image, self) constructor as well to avoid the duplicate code for assigning them in the subclasses. This is the case for RGBAImage, RGBImage, and GrayscaleImage

2018-10-30 18:25 UTC, oruebel commented on src/pynwb/image.py
> +    __nwbfields__ = ('data', 'resolution', 'description')
For GrayscaleImage ``description`` is part of the __nwbfields__ and for RGBImage, RGBAImage, and Image it is not. I assume it should not be part of the fields. I assume ``description`` should be removed from ``__nwbfields_`` in GrayscaleImage

2018-10-30 18:26 UTC, bendichter commented on src/pynwb/image.py
> +    __nwbfields__ = ('data', 'resolution', 'description')
good catch. I think it should be added

2018-10-30 18:27 UTC, bendichter commented on src/pynwb/image.py
> +        self.description = description
yeah good call

2018-10-30 18:46 UTC, oruebel submitted a review, later dismissed
Pending pass of the CI tests ;-)

2018-10-30 18:47 UTC, oruebel commented
I guess I was too soon with approving it. Looks like the CI fails. But other than the failed tests it looked good to me.

2018-10-30 19:34 UTC, bendichter commented
Do we want to enforce that `Image` is only to be used as an abstract class? i.e. an image must be declared as a `GrayscaleImage`, `RGBImage`, `RGBAImage`, or other subtype of `Image`?

2018-10-30 20:14 UTC, ajtritt commented on src/pynwb/data/nwb.base.yaml
> +- neurodata_type_def: Image
Why is Image a group and not a dataset? Making a group requires the additional dataset. This doubles the number of objects need to store an image

2018-10-30 20:51 UTC, bendichter commented
Yeah that was my original plan but I didn't know how to get Images to work
with it

On Tue, Oct 30, 2018, 4:14 PM Andrew Tritt <notifications@github.com> wrote:

> *@ajtritt* commented on this pull request.
> ------------------------------
>
> In src/pynwb/data/nwb.base.yaml
> <https://github.com/NeurodataWithoutBorders/pynwb/pull/693#discussion_r229468233>
> :
>
> > @@ -91,6 +91,24 @@ groups:
>  - neurodata_type_def: NWBDataInterface
>    neurodata_type_inc: NWBContainer
>    doc: An abstract data type for differentiating experimental data from metadata
> +- neurodata_type_def: Image
>
> Why is Image a group and not a dataset? Making a group requires the
> additional dataset. This doubles the number of objects need to store an
> image
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NeurodataWithoutBorders/pynwb/pull/693#pullrequestreview-169977815>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAziEhV_EvZLCEXDYvi74ar-j9LBW3rKks5uqLMRgaJpZM4YCgKw>
> .
>

2018-10-30 21:05 UTC, ajtritt commented
@bendichter I just submitted a PR to this branch. I thought seeing the diff would be easier than trying to explain it over text.

2018-10-31 21:43 UTC, bendichter commented
@ajtritt can you review this?

2018-10-31 22:59 UTC, ajtritt requested changes
Some extra \_\_nwbfields\_\_, but other than that it looks good.

2018-10-31 22:59 UTC, ajtritt commented on src/pynwb/image.py
> +    __nwbfields__ = ('data', 'resolution', 'description')
remove this. These properties will be inherited from the base Image class.

2018-10-31 22:59 UTC, ajtritt commented on src/pynwb/image.py
> +    __nwbfields__ = ('data', 'resolution', 'description')
remove this. These properties will be inherited from the base Image class.

2018-10-31 22:59 UTC, ajtritt commented on src/pynwb/image.py
> +    __nwbfields__ = ('data', 'resolution', 'description')
remove this. These properties will be inherited from the base Image class.

2018-11-01 01:19 UTC, merged